name: simple_note_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  signature: ^5.5.0
  path_provider: ^2.1.4
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.1
  open_file: ^3.3.0
  cloudinary_public: ^0.23.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.2.2
  shared_preferences: ^2.5.3
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
